// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVa11-NQzXACgAtHUxpmbWaPeL-9oJow',
    appId: '1:182378158590:web:c4a5a9eba53a3db66e08af',
    messagingSenderId: '182378158590',
    projectId: 'mokhi-ab045',
    authDomain: 'mokhi-ab045.firebaseapp.com',
    storageBucket: 'mokhi-ab045.firebasestorage.app',
    measurementId: 'G-C9ZKRR0RYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVw42TQLUmasR6cVAvlei49ZYjKhWBwrk',
    appId: '1:182378158590:android:ccfe7a2416df03806e08af',
    messagingSenderId: '182378158590',
    projectId: 'mokhi-ab045',
    storageBucket: 'mokhi-ab045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFapbdq_wnb5vfO8-pE4rqMST5PhsXz8',
    appId: '1:182378158590:ios:8f4048e28f922e8e6e08af',
    messagingSenderId: '182378158590',
    projectId: 'mokhi-ab045',
    storageBucket: 'mokhi-ab045.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvFapbdq_wnb5vfO8-pE4rqMST5PhsXz8',
    appId: '1:182378158590:ios:8f4048e28f922e8e6e08af',
    messagingSenderId: '182378158590',
    projectId: 'mokhi-ab045',
    storageBucket: 'mokhi-ab045.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVa11-NQzXACgAtHUxpmbWaPeL-9oJow',
    appId: '1:182378158590:web:f8cb210edeaec2fd6e08af',
    messagingSenderId: '182378158590',
    projectId: 'mokhi-ab045',
    authDomain: 'mokhi-ab045.firebaseapp.com',
    storageBucket: 'mokhi-ab045.firebasestorage.app',
    measurementId: 'G-1233HPDVE2',
  );
}
